### ISSUE TITLE
Weird Issue with Polar

### ISSUE THREAD

**Issue by ybnl2048** [Polarrco/polarr_mac_windows_support#36] opened 2016-09-25 19:05 UTC
While using Polarr via the Photo's extension if I switch to full screen the ratio of the image is strangely doubled (horizontal). If I open another image (with the extension or with the standalone app) the ratio is doubled. Desinstalling the app correct the problem. But if I switch to full screen the problem resurface (full screen within photo while using the extension). Really weird, Really Annoying!

**Comment by bwang29** [comment] 2017-11-15 00:29
Duplicate of https://github.com/Polarrco/polarr_mac_windows_support/issues/37, which was already fixed.

**Closed by bwang29** 2017-11-15 00:29 UTC
